name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        sudo apt-get install -y zlib1g-dev openjdk-8-jdk autoconf libtool pkg-config
        sudo apt-get install -y libncurses5-dev libncursesw5-dev libtinfo5 cmake
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install kivy
    
    - name: Set environment variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        echo "ANDROID_HOME=/root/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=/root/.buildozer/android/platform/android-ndk" >> $GITHUB_ENV
    
    - name: Initialize buildozer
      run: buildozer init
    
    - name: Update buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
[app]
title = Yoga Belly Fat Loss
package.name = yogabellyfat
package.domain = org.yoga
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,json,mp3,wav
version = 1.0
requirements = python3,kivy
orientation = portrait
fullscreen = 0
android.permissions = android.permission.INTERNET
android.api = 31
android.minapi = 21
android.ndk = 23b
android.ndk_api = 21
android.private_storage = True
android.accept_sdk_license = True
android.allow_backup = True
android.logcat_filters = *:S python:D
android.arch = arm64-v8a
android.allow_newer_versions = True
android.skip_update = False
android.auto_accept_sdk_license = True
EOF
    
    - name: Build APK
      run: buildozer -v android debug
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: yoga-app-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: .buildozer/logs/
        retention-days: 7 